server {
    listen 80;  # HTTP inicial (luego se agrega el bloque 443 con certificado)
    server_name tu-dominio.com;  # <-- cambiar por el dominio real

    # Todo el tráfico va a la app Gunicorn
    location / {
        proxy_pass http://anahuac-gallery:8000;
        proxy_set_header Host $host;  # conserva el dominio original
        proxy_set_header X-Real-IP $remote_addr;  # IP real del visitante
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;  # http/https original
    }

    # Validación ACME para emitir el certificado SSL
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}